services:
  app:
    build:
      context: ./desafio1
      dockerfile: Dockerfile
    container_name: desafio_app
    ports:
      - "8888:8888"
    volumes:
      - ./desafio1:/app
    command: tail -f /dev/null
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: desafio_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=CocoBambuCBLAB123@@
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: